export const GET_ALL_EMAIL_REQUEST = "GET_ALL_EMAIL_REQUEST";
export const GET_ALL_EMAIL_RECEIVED = "GET_ALL_EMAIL_RECEIVED";
export const GET_ALL_EMAIL_FAILED = "GET_ALL_EMAIL_FAILED";


export const GET_SINGLE_EMAIL_REQUEST = "GET_SINGLE_EMAIL_REQUEST";
export const GET_SINGLE_EMAIL_RECEIVED = "GET_SINGLE_EMAIL_RECEIVED";
export const GET_SINGLE_EMAIL_FAILED = "GET_SINGLE_EMAIL_FAILED";


export const MARK_FAVORITE = "MARK_FAVORITE";
export const MARK_UNFAVORITE = "MARK_UNFAVORITE";


export const READ_UP = "READ_UP";
export const UNREAD_UP = "UNREAD_UP";
export const FAVORITE_UP = "FAVORITE_UP";